### ISSUE TITLE
Can not download WMT'16 En-De

### ISSUE THREAD

**Issue by liujingcs** [HKUNLP/efficient-attention#1]
Thanks for your great work! I followed the instructions to download the WMT'16 En-De dataset. However, it appears that the dataset is currently unavailable. Would you kindly share the dataset with me?

**Comment by LZhengisme** [comment]
Hi,

Thanks for your notice! It seems that the original drive link provided by Google is broken (see e.g. https://github.com/facebookresearch/fairseq/issues/4192
and https://github.com/facebookresearch/fairseq/issues/4454). Unfortunately, I do not store a copy of the original `wmt16_en_de.tar.gz`; but there is a binarized copy of data (that is, `fairseq-preprocessed` data) available on [this link](https://drive.google.com/file/d/1ZSKYYT1Z3FdlqmR9EXqdmsB0ccbxO7W6/view?usp=sharing). 

Hope this could be useful!

**Comment by liujingcs** [comment]
Thanks for your reply. I will use the binarized copy of data.
